######################################################################
# Automatically generated by qmake (2.01a) Tue Jul 8 19:59:30 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += “/Users/daniel/opencv/include”
LIBS += -L"/Users/daniel/opencv/lib/" -lopencv_core -lopencv_highgui

SOURCES += main.cpp QOpenCVWidget.cpp MyCameraWindow.cpp
HEADERS += MyCameraWindow.h \
    QOpenCVWidget.h

FORMS +=

